
RSpec.describe Like, type: :model do
  describe 'test for presence of model attributes generated by the polymorphic associatons' do
    let(:like) { FactoryBot.create(:like) }

    it 'should include likeable_id attribute' do
      expect(like.attributes).to include('likeable_id')
    end

    it 'should include likeable_type attribute' do
      expect(like.attributes).to include('likeable_type')
    end
  end
end
